### ISSUE TITLE
PKI

### ISSUE THREAD

**Issue by zhu011** [PKINet/PKINet#1]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

尊敬的作者：
十分感谢您做出的工作，下面关于您的论文我有一点疑惑，关于PKI Module为何设置为5，7，9，11这样的尺寸，有什么理论支持这种尺寸设置，其它尺寸设置是否可以？

**Comment by PKINet** [comment]
Thank you for your attention!

You can refer to Table 8(a) and Chapter 4.4 **Multi-scale Kernel Design** for more details. Feel free to ask more about this setting.
