### ISSUE TITLE
[Feature] log 

### ISSUE THREAD

**Issue by ZhenboZhao77** [PKINet/PKINet#11]
### What's the feature?

Dear Author,

It is a pleasure to read your article on pkinet. I am currently facing some issues using pki as the backbone for my model. Could you please share the log files of your training? I would like to see the details of the first few training epochs.

Thank you.

**Comment by ZhenboZhao77** [comment]
Since all my experiments were conducted with max_epochs = 12, how much improvement can be expected if max_epochs is increased to 30？

**Comment by PKINet** [comment]
Sure, this is the training log of PKINet-S with Oriented R-CNN in DOTA-1.0 [20231105_214905.log](https://github.com/user-attachments/files/16598304/20231105_214905.log). We suggest following the same setting with our paper to get the best performance.

**Comment by ZhenboZhao77** [comment]
thank you.
