### ISSUE TITLE
[Feature]有关于CCA模块的问题

### ISSUE THREAD

**Issue by anhuidinglieqiaodaima** [PKINet/PKINet#13]
### What's the feature?

在CCA模块中，为什么会使用1×1卷积和平均池化，难道只是为了局部特征吗？

**Comment by Strike1999** [comment]
It is common practice to apply a 1x1 convolution following a depth-wise convolution. In our CAA module, the paired depth-wise convolution can be interpreted as spatial attention, while the 1x1 convolution can be viewed as channel attention.

**Comment by PKINet** [comment]
It is common practice to apply a 1x1 convolution following a depth-wise convolution. In our CAA module, the paired depth-wise convolution can be interpreted as spatial attention, while the 1x1 convolution can be viewed as channel attention.

**Comment by anhuidinglieqiaodaima** [comment]
Thank you for your reply.
What is the purpose of average pooling and 1×1 convolution before a pair of deep convolutions?

**Comment by PKINet** [comment]
The primary motivation behind designing CAA is to capture long-range contextual information. By placing an AvgPool layer before the paired depth-wise convolution, we further expand the receptive field of CAA, enabling it to capture more comprehensive information. A 1x1 convolution following the pooling enhances the feature representation by linearly combining and re-weighting the channels of each pixel.

**Comment by anhuidinglieqiaodaima** [comment]
Thank you very much for your reply!
In the final stage, sigmoid function is used to enhance the output of the PKI module. Can it be interpreted as enhancing the PKI module's ability to capture global context information?

**Comment by PKINet** [comment]
If you are referring to the sigmoid function in the CAA module, its purpose is to ensure that the values of the attention map are constrained within the range [0,1].

**Comment by anhuidinglieqiaodaima** [comment]
You mean generating [0, 1] weights, so why can the PKI module be enhanced?

**Comment by PKINet** [comment]
The purpose of restricting the CAA attention value to the range [0,1] is to prevent the impact of CAA from being too large or too small. After that, it can be combined with the PKI module.

**Comment by PKINet** [comment]
This issue is temporarily closed due to inactivity. Feel free to reopen it.

**Comment by anhuidinglieqiaodaima** [comment]
Why can the CCA module further enhance the output of the PKI module?




.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PKINet/PKINet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月13日(星期天) 上午10:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PKINet/PKINet] [Feature]有关于CCA模块的问题 (Issue #13)





 
The purpose of restricting the CAA attention value to the range [0,1] is to prevent the impact of CAA from being too large or too small. After that, it can be combined with the PKI module.
