### ISSUE TITLE
[scheduler]  The training strategy on DIOR-R dataset

### ISSUE THREAD

**Issue by BasilLeave** [PKINet/PKINet#15]
### Model/Dataset/Scheduler description

Excuse me, I am trying to reproduce the accuracy of PKINet in DIOR-R dataset.  What is the training strategy on DIOR-R dataset? Could you provide relevant configuration files

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available.

**Comment by PKINet** [comment]
This issue has been solved by E-mail.

**Comment by Sonettoo** [comment]
Hello,
I am currently attempting to reproduce the accuracy of PKINet on the DIOR-R dataset. To effectively replicate the experimental results, I would like to request a copy of the training configuration file or related training strategy information for the DIOR-R dataset.
I noticed that a similar question was raised on GitHub, and it was resolved via email. If possible, could you kindly provide me with the configuration information for the DIOR-R dataset? This would be extremely helpful for my experimental work.
Thank you very much
