### ISSUE TITLE
Why the PKIBlock has an FNN operation?

### ISSUE THREAD

**Issue by Sudae827** [PKINet/PKINet#3]
### What's the feature?

Thank you for your outstanding work. I have a question regarding why there is an FFN operation in the PKLBlock (refer to lines 262, 265, 269, and 272). Do I miss something in the paper?

    def forward(self, x):
        if self.layer_scale:
            if self.add_identity:
                x = x + self.drop_path(self.gamma1.unsqueeze(-1).unsqueeze(-1) * self.block(self.norm1(x)))
                **x = x + self.drop_path(self.gamma2.unsqueeze(-1).unsqueeze(-1) * self.ffn(self.norm2(x)))**
            else:
                x = self.drop_path(self.gamma1.unsqueeze(-1).unsqueeze(-1) * self.block(self.norm1(x)))
                **x = self.drop_path(self.gamma2.unsqueeze(-1).unsqueeze(-1) * self.ffn(self.norm2(x)))**
        else:
            if self.add_identity:
                x = x + self.drop_path(self.block(self.norm1(x)))
                **x = x + self.drop_path(self.ffn(self.norm2(x)))**
            else:
                x = self.drop_path(self.block(self.norm1(x)))
                **x = self.drop_path(self.ffn(self.norm2(x)))**
        return x

**Comment by PKINet** [comment]
Thanks for your interest!

This is a common design for the backbone and is not directly related to our core module, so we have omitted it from the manuscript. You can refer to LSKNet [https://github.com/zcablii/LSKNet/blob/main/mmrotate/models/backbones/lsknet.py](url) (line 102-103).
