### ISSUE TITLE
[New Models] The problem of PKINet-S pre-training weight

### ISSUE THREAD

**Issue by jiubie89** [PKINet/PKINet#7]
### Model/Dataset/Scheduler description

I want to download your PKINet-S pre-training weights, but your github link shows an error, do you have another way to download? Looking forward to your reply

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available.

**Comment by PKINet** [comment]
The link is now working properly. Also, I provide a Baidu Cloud link:

https://pan.baidu.com/s/1ZGVE4g1-ww00pBEfbZPWhQ?pwd=raem

**Comment by jiubie89** [comment]
> The link is now working properly. Also, I provide a Baidu Cloud link:
> 
> https://pan.baidu.com/s/1ZGVE4g1-ww00pBEfbZPWhQ?pwd=raem

谢谢
