### ISSUE TITLE
[New Models]PKINet-S Pre-training weigth link not working

### ISSUE THREAD

**Issue by Spike0424** [PKINet/PKINet#9]
### Model/Dataset/Scheduler description

I want to download your PKINet-S pre-training weights, but your github link shows an error, do you have another way to download? Looking forward to your reply

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available.

**Comment by PKINet** [comment]
It's strange because everything looks fine to me. I provide a Baidu Cloud link:

https://pan.baidu.com/s/1ZGVE4g1-ww00pBEfbZPWhQ?pwd=raem

**Comment by Spike0424** [comment]
Thank you so much.Baidu Cloud link is working.
